name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    name: Unit Test
    strategy:
      matrix:
        go-version: [1.25.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Test
        run: |
          go test ./... -coverprofile=coverage.out -count=1 -v

      - name: Generate coverage report
        run: go tool cover -func=coverage.out

      - name: Update coverage report and badge
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: coverage.out
          report: true
          chart: true
          amend: true
        continue-on-error: true

  # Deploy:
  #   name: Deploy application
  #   needs: [Test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: akhileshns/heroku-deploy@v3.12.14
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: "wellingtonlope-ticket-api"
  #         heroku_email: "wellington.lopes.tw@gmail.com"
  #         usedocker: true
  #         docker_build_args: |
  #           APP_ENV
  #           APP_SECRET
  #           TOKEN_DURATION_HOUR
  #           MONGO_URI
  #           MONGO_DATABASE
  #       env:
  #         APP_ENV: production
  #         APP_SECRET: ${{secrets.API_SECRET}}
  #         TOKEN_DURATION_HOUR: ${{secrets.TOKEN_DURATION_HOUR}}
  #         MONGO_URI: ${{secrets.MONGO_URI}}
  #         MONGO_DATABASE: ticket-api
