name: Build

on:
  push:
    branches:
      - main

jobs:
  Test:
    name: Unit Test
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Unit Test
        run: go test -v ./... -coverprofile=coverage.out

      - name: Run Coverage
        run: go tool cover -func=coverage.out

  Deploy:
    name: Deploy application
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "wellingtonlope-ticket-api"
          heroku_email: "wellington.lopes.tw@gmail.com"
          usedocker: true
          docker_build_args: |
            APP_ENV
            APP_SECRET
            TOKEN_DURATION_HOUR
            MONGO_URI
            MONGO_DATABASE
        env:
          APP_ENV: production
          APP_SECRET: ${{secrets.API_SECRET}}
          TOKEN_DURATION_HOUR: ${{secrets.TOKEN_DURATION_HOUR}}
          MONGO_URI: ${{secrets.MONGO_URI}}
          MONGO_DATABASE: ticket-api